spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/momosteps
  batch:
    job:
      names: calculateWeeklyStepsJob

  kafka:
    bootstrap-servers: localhost:9092

momosteps:
  batch:
    page-size: 1000

redis:
  host: localhost
  port: 6379

